# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 256f219eeaecbd9ee62fc7d5aada3a4ca7f1f971a4de56859beb9de0ffba7dc075a3754739d7e96fd45448d365e2c8d067bd152d8aec5df2bd8e4b78b95a8edf

test:
  secret_key_base: 239a3fe5958af188a41d69054f83028b9490bb921f14c4434c99dc8c139c42e7b93f27914f527804de734cf0bad1a8e3a3904927629df2e320dcf329ca965a5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
